### ISSUE TITLE
Add Brigade CI

### ISSUE THREAD

**Issue by radu-matei** [deislabs/cnab-netstandard#5]
We need to create a new Brigade project on the CI instance we use for other projects and create a test pipeline for it.

I volunteer to create the test pipeline. @vdice could you please help setting up the Brigade project?

**Comment by vdice** [comment]
Project created: https://azure.github.io/kashti/projects/brigade-599c2f92120cd7feeaa6fad1b96de7c0a170eb9dd47d2e10203f37

Should be ready for testing!
